# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-S-AztoZbVFGNP7mPfKSfsfQgfXY4yOg
"""

print("\033[32mWelcome to Compound-Interest-Calculation Module by Adnan Alam Khan\033[0m")


Principal = int(input("Please enter the amount of initial Investment in $: "))
Rate = float(input("Please enter the annual interest rate (as a decimal): "))
Target = int(input("Please enter the target amount in $: "))
Years = 0


while Principal < Target:
    Principal += Principal * Rate
    Years += 1

print(f"It will take {Years} years for the investment to reach or exceed {Target}.")